import type { CookieRecord } from './types.js';
import { BrowserToolError } from '../domain.js';

/**
 * Converts a list of CookieRecords into standard Netscape cookies.txt format.
 */
export function cookiesToNetscape(cookies: readonly CookieRecord[]): string {
  const lines: string[] = [
    '# Netscape HTTP Cookie File',
    '# https://curl.se/docs/http-cookies.html',
    '# This file was generated by Compliant Fingerprint Browser',
    '',
  ];

  for (const cookie of cookies) {
    const domain = cookie.domain || '';
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.expires ? Math.floor(cookie.expires) : 0;
    const name = cookie.name || '';
    const value = cookie.value || '';

    lines.push(`${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}`);
  }

  return lines.join('\n') + '\n';
}

/**
 * Parses Netscape cookies.txt string into CookieRecord array.
 */
export function parseNetscapeCookies(content: string): CookieRecord[] {
  const result: CookieRecord[] = [];
  const lines = content.split(/\r?\n/);

  for (let lineIndex = 0; lineIndex < lines.length; lineIndex++) {
    const rawLine = lines[lineIndex];
    if (!rawLine) continue;
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const parts = line.split('\t');
    if (parts.length < 7) {
      continue;
    }

    const domain = parts[0] ?? '';
    const path = parts[2] ?? '/';
    const securePart = parts[3] ?? '';
    const secure = securePart.toUpperCase() === 'TRUE';
    const expiresPart = parts[4] ?? '0';
    const expires = parseInt(expiresPart, 10);
    const name = parts[5] ?? '';
    const value = parts.slice(6).join('\t');

    result.push({
      name,
      value,
      domain,
      path,
      ...(isNaN(expires) || expires <= 0 ? {} : { expires }),
      secure,
      httpOnly: false,
      sameSite: 'Lax',
    });
  }

  return result;
}

/**
 * Normalizes cookies from either JSON string/array or Netscape format into CookieRecord[]
 */
export function parseCookies(raw: string | readonly CookieRecord[], format: 'json' | 'netscape' = 'json'): CookieRecord[] {
  if (Array.isArray(raw)) {
    return raw as CookieRecord[];
  }

  if (typeof raw !== 'string') {
    throw new BrowserToolError('INVALID_ARGUMENT', 'Cookies must be a string or array.');
  }

  const trimmed = raw.trim();
  if (!trimmed) {
    return [];
  }

  if (format === 'netscape' || trimmed.startsWith('# Netscape') || (!trimmed.startsWith('[') && !trimmed.startsWith('{') && trimmed.includes('\t'))) {
    return parseNetscapeCookies(trimmed);
  }

  try {
    const parsed = JSON.parse(trimmed);
    const cookiesArray = Array.isArray(parsed) ? parsed : (parsed.cookies || []);
    if (!Array.isArray(cookiesArray)) {
      throw new Error('Invalid JSON structure; expected an array of cookie objects.');
    }
    return cookiesArray.map((c: any) => ({
      name: String(c.name || ''),
      value: String(c.value || ''),
      domain: String(c.domain || ''),
      path: String(c.path || '/'),
      expires: typeof c.expires === 'number' ? c.expires : undefined,
      httpOnly: Boolean(c.httpOnly),
      secure: Boolean(c.secure),
      sameSite: (c.sameSite === 'Strict' || c.sameSite === 'Lax' || c.sameSite === 'None') ? c.sameSite : undefined,
    }));
  } catch (err: unknown) {
    throw new BrowserToolError('INVALID_ARGUMENT', `Failed to parse cookies JSON: ${err instanceof Error ? err.message : String(err)}`);
  }
}
